#1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod-moti
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
          
---
     #2 
apiVersion: apps/v1
kind: Deployment
metadata:
    name: messaging
    labels:
    tier: msg
spec:
    replicas: 1
    selector:
    matchLabels:
        tier: msg
    template:
    metadata:
        labels:
        tier: msg
    spec:
        containers:
        - name: messaging
        image: redis:alpine
        ports:
---
    #3 kubectl create namespace apx-x998-moti
    #4 kubectl get nodes -o json >> ./tmp/nodes-moti
    #5 kubectl expose deployment messaging  --port=80 --protocol=TCP --target-port=6379 --name=messaging-service  --type=clusterIp
     
    #6
    apiVersion: v1
    kind: Service
    metadata:
      name: messaging-service
    spec:
      type: ClusterIp
      selector:
        tier: msg
      ports:
        - protocol: TCP
          port: 80
          targetPort: 6379 
---
    #7
    apiVersion: apps/v1
    kind: Deployment
    metadata:
        name: hr-web-app
        labels:
        app: hr-web-app
    spec:
        replicas: 2
        selector:
        matchLabels:
            app: hr-web-app
        template:
        metadata:
            labels:
            app: hr-web-app
        spec:
            containers:
            - name: hr-web-app
              image: kodekloud/webapp-color
---
#8 
apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
  labels:
spec:
  containers:
    - name: static-busybox
      image: busybox
      command: ['sh', '-c', ' sleep 1000']   
---
  #9
  
apiVersion: v1
kind: Pod
metadata:
  name: temp-bus
  namespace: finance-moti
  labels:
    name: temp-bus
spec:
  containers:
  - name: temp-bus
    image: redis:alpine
 
---
  #10
  
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-analytics
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostpath:
    path: /pv/data-analytics
---
  #11
apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-moti
spec:
  containers:
  - image: redis:alpine
    name: redis-storage-moti
    volumeMounts:
    - mountPath: /data/redis
      name: redis-storage-moti
  volumes:
  - name: redis-storage-moti
    emptyDir: {}
  
  



                
